# Generated by Django 4.0.5 on 2023-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_author_book_is_bestselling_alter_book_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
